### ISSUE TITLE
use gcc

### ISSUE THREAD

**Issue by 892768447** [yan12125/python3-android#10]
hello, It's easy to use gcc to compile python without clang?

**Comment by yan12125** [comment]
If you are looking for a script that uses GCC to build Python for Android, https://github.com/GRRedWings/python3-android is a good alternative. In my repo, clang is the only option as Android NDK has deprecated GCC for a long time and they're going to remove it soon.

**Comment by 892768447** [comment]
the GRRedWings/python3-android is ok,
and I follow your source,Step by step,Successfully compiled openssl,zlib,xz,sqlite3,readline,lzma...
but when I compile python,
1: patch the python
2: autoreconf --install --verbose --force
3: export CONFIG_SITE=../python/config.site
4: add Third party dependence path to CPPFLAGS CFLAGS CXXFLAGS LDFLAGS
5: ./configure --prefix=$SYSROOT --host=arm-linux-androideabi --build=x86_64-linux-gnu --disable-ipv6 --with-system-ffi --with-system-expat --without-ensurepip
6: make && make altinstall
The result is not what I expected, It's just compile python and it can run on the phone, but the lib-dynload folder is empty,no so file in it,
the _ssl.so _lzma.so readline.so...can't compile.
how can i do?

**Comment by yan12125** [comment]
Please paste as many details as possible, including contents of binaries like ```CC```, ```LD``` and ```*FLAGS``` as well as error messages in compiling ```*.so```.

But, why are you sticking to GCC :/

**Comment by GRRedWings** [comment]
Also, clang is the direction I plan to go as soon as I get the time to convert. I'm trying to piece together a lot of what was done here because I'm not one to re-invent the wheel.  

I'm also fearful that my attempt to convert my Android project from experimental gradle to cmake would benefit from Python3 being clang

**Comment by 892768447** [comment]
I try modify the openssl patch, finally successed compiled openssl,sqlite,lzma,readline..etc...
but, I find some error when compile python. it's look likes  (  crtbegin_dynamic.o:crtbegin.c:function _start: error: undefined reference to 'main'  )
I search this msg on google, some posts suggest to add -shared. but I find it already in the command line.and it no useful.
the next step,I will try to use standalone-toolchain,maybe ok.

here is the error message:
`/home/irony/soft/Android/android-ndk-r16-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -shared --sysroot=/home/irony/soft/Android/android-ndk-r16-beta1/platforms/android-21/arch-arm/usr -pie -L /home/irony/Python/build/target/openssl/usr/lib -L /home/irony/Python/build/target/ncurses/usr/lib -L /home/irony/Python/build/target/readline/usr/lib -L /home/irony/Python/build/target/sqlite/usr/lib -L /home/irony/Python/build/target/bzip2/usr/lib -L /home/irony/Python/build/target/xz/usr/lib -L /home/irony/Python/build/target/gdbm/usr/lib -L /home/irony/Python/build/target/libffi/usr/lib -L /home/irony/Python/build/target/zlib/usr/lib -L /home/irony/Python/build/target/expat/usr/lib -L /home/irony/Python/build/target/tools/usr/lib -L/home/irony/soft/Android/android-ndk-r16-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/lib -L/home/irony/soft/Android/android-ndk-r16-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc build/temp.linux-arm-3.7/home/irony/Python/src/v3.7.0a1/Modules/_struct.o -o build/lib.linux-arm-3.7/_struct.cpython-37m.so
/home/irony/soft/Android/android-ndk-r16-beta1/platforms/android-21/arch-arm/usr/lib/crtbegin_dynamic.o:crtbegin.c:function _start: error: undefined reference to 'main'`

**Comment by yan12125** [comment]
Adding ```-shared``` sounds a reasonable advice. I have no idea why this command fails. You may need to debug that by yourself.

**Comment by 892768447** [comment]
I find the reason, because of '-pie', From Android L, It check the binary file with pie.
when I use gcc compile python, i add pie in wrong place.it cause build python ext failed.
1. modify python.py

    LDFLAGS = self.env['LDFLAGS']
    LDFLAGS.remove('-pie')
    self.env['LDFLAGS'] = LDFLAGS

this step will build python ext ok

2. patch Makefile

sed -i 's/^\t$(LINKCC) $(PY_LDFLAGS) $(LINKFORSHARED) -o $@ Programs\/python.o/\t$(LINKCC) $(PY_LDFLAGS) $(LINKFORSHARED) -fPIE -pie -o $@ Programs\/python.o/' Makefile

sed -i 's/^\t$(MAINCC) -c $(PY_CORE_CFLAGS) -o $@ $(srcdir)\/Programs\/python.c$/\t$(MAINCC) -c $(PY_CORE_CFLAGS) -fvisibility=default -fPIE -o $@ $(srcdir)\/Programs\/python.c/' Makefile

this step for python binary file

**Comment by 892768447** [comment]
Thanks very much for this project
