### ISSUE TITLE
Investigate LibreSSL

### ISSUE THREAD

**Issue by yan12125** [yan12125/python3-android#12]
Python supports both OpenSSL and LibreSSL. They are intensively tested in [CPython's test suite](https://github.com/python/cpython/blob/master/Tools/ssl/multissltests.py).

Pros of LibreSSL:
1. It uses autotools and CMake instead of home-grown Perl-based build system. Life should be easier without all the OpenSSL build system hacking.
2. Claims to be more secure

Cons of LibreSSL:
1. Less features. For example [it doesn't support TLS 1.3 yet](https://github.com/libressl-portable/portable/issues/228). It might be good as there won't be a bug like https://github.com/openssl/openssl/pull/1979

**Comment by yan12125** [comment]
Current progress:

1. Builds fine
2. SSL root CAs doesn't work. With OpenSSL, ```$SSL_CERT_DIR``` can be used to specify the path to root CA certificates. LibreSSL removed this ability https://github.com/openbsd/src/commit/920ccb623f2ff40701397bf8b898c6ebdf3a73a1#diff-ac1a59cd86babe3c58aeb69614f533b3. That's good :) If we can specify root CA simply by environment variables, we can run MITM attacks easily.

Issues:
1. LibreSSL ships its own cert.pem. Should it be used or just importing certificates from the Android system?
2. LibreSSL might not be compatible with Python 3.7 https://bugs.python.org/issue31399 https://github.com/libressl-portable/portable/issues/381

**Comment by tiran** [comment]
The majority of Python core developers uses OpenSSL to develop, test and verify ssl module. CPython's Windows and macOS installer ships OpenSSL. CPython's CI does not run tests with LibreSSL. I'm the primary maintainer of CPython's ssl module and prefer OpenSSL.

``SSL_CERT_DIR`` is not a serious attack vector. If an attack is able to inject env vars into your process, then you have more serious issues. If you are worried about the env var, then you can simple unset it or specify explicit paths.

I highly recommend that you use the system's trust store.

**Comment by yan12125** [comment]
My idea was based on that LibreSSL is _as good as_ OpenSSL, so my life is easier without worrying about OpenSSL's custom Perl-based build system. Now I learn that LibreSSL is missing some important function. Unless https://github.com/libressl-portable/portable/issues/381 is fixed before Python 3.7 released, I won't consider switching to LibreSSL.

> I highly recommend that you use the system's trust store.

Thanks for the suggestion. That's what I do in the master branch.

**Comment by tiran** [comment]
You don't need Perl to compile OpenSSL. You just need Perl to create some files. For CPython's Windows builds, we used to pre-generate files on a machine with ActiveState Perl installed. The build and test machines then used the pre-generated files.

**Comment by yan12125** [comment]
Having a working Perl interpreter is not an issue - I always build CPython for Android on Linux or macOS. The problem is that OpenSSL's Android support requires quite a few changes and I need to learn Perl for creating sensible patches.

**Comment by yan12125** [comment]
OpenSSL has completed its Android support, so switching to LibreSSL is not a plan anymore.

Ref: 54eafde8dd3213c0f4bc4325f396748337dc884d
