### ISSUE TITLE
Deploy Result To GH-Pages

### ISSUE THREAD

**Issue by TheBrokenRail** [yan12125/python3-android#15]

**Comment by yan12125** [comment]
Hmm, what kind of results?

**Comment by TheBrokenRail** [comment]
Since Travis CI already builds the .so and .a fles you could upload the results so anyone could download the files from GH-Pages.

**Comment by yan12125** [comment]
Built Python tarballs will be available in https://dl.chyen.cc/python3-android/ with the name scheme `python-<arch>-<python_ver>-<android_api_level>-<ndk_ver>.tar.bz2`. For example, `python-arm-3.8.0a0.r102798.353933e712-android21-ndk_19.0.5106443-beta1.tar.bz2`.
