### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#17]
I'm trying to build the project, and I get the following error.  Any ideas?

/Users/Brian/python-files/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang -E -P -DHAVE_CONFIG_H   -I./linux/arm -I./linux/arm -I./linux -I./linux -I. -I.     -I/Users/Brian/python3-android-yan/build/sysroot/usr/include -DIN_MPERS_BOOTSTRAP v4l2.c -o v4l2.c.mpers.i
echo '/* Generated by Makefile from block.c.mpers.i btrfs.c.mpers.i dirent.c.mpers.i evdev_mpers.c.mpers.i fetch_bpf_fprog.c.mpers.i fetch_struct_flock.c.mpers.i fetch_struct_keyctl_kdf_params.c.mpers.i fetch_struct_mmsghdr.c.mpers.i fetch_struct_msghdr.c.mpers.i fetch_struct_stat.c.mpers.i fetch_struct_stat64.c.mpers.i fetch_struct_statfs.c.mpers.i fetch_struct_xfs_quotastat.c.mpers.i hdio.c.mpers.i ipc_msgctl.c.mpers.i ipc_shmctl.c.mpers.i loop.c.mpers.i mtd.c.mpers.i perf_ioctl.c.mpers.i print_aio_sigset.c.mpers.i print_group_req.c.mpers.i print_mq_attr.c.mpers.i print_msgbuf.c.mpers.i print_sg_req_info.c.mpers.i print_sigevent.c.mpers.i print_time.c.mpers.i print_timespec.c.mpers.i print_timeval.c.mpers.i print_timex.c.mpers.i printrusage.c.mpers.i printsiginfo.c.mpers.i rt_sigreturn.c.mpers.i rtc.c.mpers.i sg_io_v3.c.mpers.i sigaltstack.c.mpers.i sock.c.mpers.i sysinfo.c.mpers.i times.c.mpers.i ustat.c.mpers.i utime.c.mpers.i v4l2.c.mpers.i; do not edit. */' > native_printer_decls.h-t
for f in block.c.mpers.i btrfs.c.mpers.i dirent.c.mpers.i evdev_mpers.c.mpers.i fetch_bpf_fprog.c.mpers.i fetch_struct_flock.c.mpers.i fetch_struct_keyctl_kdf_params.c.mpers.i fetch_struct_mmsghdr.c.mpers.i fetch_struct_msghdr.c.mpers.i fetch_struct_stat.c.mpers.i fetch_struct_stat64.c.mpers.i fetch_struct_statfs.c.mpers.i fetch_struct_xfs_quotastat.c.mpers.i hdio.c.mpers.i ipc_msgctl.c.mpers.i ipc_shmctl.c.mpers.i loop.c.mpers.i mtd.c.mpers.i perf_ioctl.c.mpers.i print_aio_sigset.c.mpers.i print_group_req.c.mpers.i print_mq_attr.c.mpers.i print_msgbuf.c.mpers.i print_sg_req_info.c.mpers.i print_sigevent.c.mpers.i print_time.c.mpers.i print_timespec.c.mpers.i print_timeval.c.mpers.i print_timex.c.mpers.i printrusage.c.mpers.i printsiginfo.c.mpers.i rt_sigreturn.c.mpers.i rtc.c.mpers.i sg_io_v3.c.mpers.i sigaltstack.c.mpers.i sock.c.mpers.i sysinfo.c.mpers.i times.c.mpers.i ustat.c.mpers.i utime.c.mpers.i v4l2.c.mpers.i; do \
		sed -r -n 's/^MPERS_PRINTER_DECL\(([^,)]+),[[:space:]]*([^,)]+),[[:space:]]*([^)]+)\)$/extern \1 \2(\3);/p' $f \
		|| exit; \
	done >> native_printer_decls.h-t
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
make[1]: *** [native_printer_decls.h] Error 1
rm ioctlsort0 ioctlsort0.o ioctls_all0.h
Traceback (most recent call last):
  File "/usr/local/Cellar/python/HEAD-b6ef6f6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python/HEAD-b6ef6f6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Brian/python3-android-yan/pybuild/__main__.py", line 3, in <module>
    main()
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 52, in main
    build_package('python')
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 36, in build_package
    build_package(dep)
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 44, in build_package
    pkg.build()
  File "/Users/Brian/python3-android-yan/pybuild/packages/strace.py", line 21, in build
    self.run(['make'])
  File "/Users/Brian/python3-android-yan/pybuild/package.py", line 108, in run
    self.source.run_in_source_dir(cmd, *args, **kwargs)
  File "/Users/Brian/python3-android-yan/pybuild/source.py", line 52, in run_in_source_dir
    return run_in_dir(cmd, self.source_dir, env, mode)
  File "/Users/Brian/python3-android-yan/pybuild/util.py", line 65, in run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/usr/local/Cellar/python/HEAD-b6ef6f6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 348, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

**Comment by yan12125** [comment]
Some workarounds come to my mind: remove strace from env.py; installing GNU sed and prepending it to $PATH.
