### ISSUE TITLE
ncurses error

### ISSUE THREAD

**Issue by aiadaniel** [yan12125/python3-android#20]
/bin/sh ./run_tic.sh
** Building terminfo database, please wait...
Running tic to install /home/lxm/python3-android-master/build/sysroot/usr/share/terminfo ...

        You may see messages regarding extended capabilities, e.g., AX.
        These are extended terminal capabilities which are compiled
        using
                tic -x
        If you have ncurses 4.2 applications, you should read the INSTALL
        document, and install the terminfo without the -x option.

"terminfo.tmp", line 1115, col 36, terminal 'fbterm': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4785, col 36, terminal 'xterm+256color': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4804, col 36, terminal 'xterm+256setaf': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4848, col 25, terminal 'xterm+direct2': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4848, col 40, terminal 'xterm+direct2': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4863, col 25, terminal 'xterm+direct': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4863, col 40, terminal 'xterm+direct': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4885, col 25, terminal 'xterm+indirect': limiting value of `colors' from 0x1000000 to 0x7fff
"terminfo.tmp", line 4885, col 40, terminal 'xterm+indirect': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 7597, col 36, terminal 'dvtm-256color': limiting value of `pairs' from 0x10000 to 0x7fff
"terminfo.tmp", line 4775, terminal 'xterm-16color': error writing /home/lxm/python3-android-master/build/sysroot/usr/share/terminfo/x/xterm-16color
? tic could not build /home/lxm/python3-android-master/build/sysroot/usr/share/terminfo
make[2]: *** [install.data] Error 1
make[2]: Leaving directory `/home/lxm/python3-android-master/src/ncurses-snapshots/misc'
make[1]: *** [install] Error 2

**Comment by aiadaniel** [comment]
I have build ncurses-6.1 & make install,do I have to set something else?  On CentOS7

**Comment by yan12125** [comment]
aiadaniel <notifications@github.com> 於 2019年8月21日 週三 下午2:56寫道：
>
> I have build ncurses-6.1 & make install,do I have to set something else? On CentOS7
>

Hi, could you check whether `tic -V` prints a recently enough version
or not? (e.g., 6.1.YYYYmmdd) If not you may want to tweak $PATH.

**Comment by aiadaniel** [comment]
> aiadaniel <notifications@github.com> 於 2019年8月21日 週三 下午2:56寫道：
> I have build ncurses-6.1 & make install,do I have to set something else? On CentOS7
> Hi, could you check whether `tic -V` prints a recently enough version or not? (e.g., 6.1.YYYYmmdd) If not you may want to tweak $PATH.
> […](#)
> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

It is ncurses 6.1.20180127

**Comment by yan12125** [comment]
Hmm 6.1.20180127 should work. Anyway, could you try ncurses 6.1.20190121 or newer? It might still be broken, but it should provide better error messages. Instead of the current message:

> "terminfo.tmp", line 4775, terminal 'xterm-16color': error writing /home/lxm/python3-android-master/build/sysroot/usr/share/terminfo/x/xterm-16color

6.1.20190121 or newer will give a mesage like this:

>  "terminfo.tmp", line 4775, terminal 'xterm-16color': error writing /home/lxm/python3-android-master/build/sysroot/usr/share/terminfo/x/xterm-16color: _(reason for the failure)_

**Comment by yan12125** [comment]
I created a docker image for easier setup of the build environment: https://github.com/yan12125/python3-android#build-using-docker.

If you found how to build this repository on CentOS 7 natively (i.e., without docker), feel free to propose it.
