### ISSUE TITLE
There isn't send.sh in devscripts

### ISSUE THREAD

**Issue by edips** [yan12125/python3-android#21]
Hello. I built Python 3.9. I would run it on Android but there isn't send.sh in master. It was in old branches. Is there any update about the script for sending Python files to Android?
Thanks.

**Comment by yan12125** [comment]
Thank you very much for noticing this! Yes I rewrite `send.sh` in Python a while ago and now I use `python -m pybuild.send` to send built files. However, it is not quite robust, so I decide to replace the command with manual instructions.

**Comment by edips** [comment]
Thanks for the update.
