### ISSUE TITLE
Build Using Docker on Windows

### ISSUE THREAD

**Issue by canewsin** [yan12125/python3-android#22]
Docker is Available on windows so please provide a script to run with docker on windows

**Comment by yan12125** [comment]
I don't have a Windows machine for development, so I will not be able to do that in near future. Patches are still welcome, of course.

**Comment by canewsin** [comment]
i was getting this error
```
C:\Users\PramUkesh>docker run --detach --name python-builder --volume "/home/python3-android" --tty "yan12125/python3-android-base"
Unable to find image 'yan12125/python3-android-base:latest' locally
docker: Error response from daemon: pull access denied for yan12125/python3-android-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by canewsin** [comment]
@yan12125

**Comment by yan12125** [comment]
Oh yeah I stopped maintaining the yan12125/python3-android-base image on docker hub due to maintenance issues. I will update the instructions.

**Comment by canewsin** [comment]
how can i build docker image from some base

**Comment by yan12125** [comment]
canewsin <notifications@github.com> 於 2020年1月9日 週四 上午3:16寫道：
>
> how can i build docker image from some base
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

I fixed the Dockerfile and relevant instructions.

**Comment by yan12125** [comment]
I haven't tried building on Windows, but docker images should work everywhere. Feel free to leave comments if there are still issues.
