### ISSUE TITLE
Clean Source Repo instead of make clean

### ISSUE THREAD

**Issue by canewsin** [yan12125/python3-android#27]
Sometimes, internet connection is not reliable, and some places internet is very costly,
make clean will delete all src folder so if we build for all arch for android it sometimes took up to 4gb data to download, even you have speed internet connection, it doesn't make sense to delete and download repo so many times. use some tools like git to reset repos to official commits and cache zip files for non git repos.

I almost spent more than 20 GB data last month to clean compile the repo, so requesting this feature.

**Comment by yan12125** [comment]
Thanks for the suggestion. I did maintain similar functionality, but I abandon it as it brought maintenance costs and made modifying building scripts complex [1]. You may want to write your own scripts if you wish.

[1] https://github.com/yan12125/python3-android/commit/66dab41103bf2275b44b04c5a68db20f97b95733
