### ISSUE TITLE
Possibility to build last stable python version

### ISSUE THREAD

**Issue by mkalinowski2** [yan12125/python3-android#29]
Hi, is there any possibility to build last stable python version?

**Comment by yan12125** [comment]
Thanks for the proposal. I have been considering this for some time due to lack of time chasing CPython git master. I will do this when 3.9.0 is out.

**Comment by mkalinowski2** [comment]
Thanks, it would be great :)

**Comment by yan12125** [comment]
Here comes shiny 3.9.0, with prebuilt binaries! https://github.com/yan12125/python3-android/releases/tag/3.9.0-android1

**Comment by mkalinowski2** [comment]
@yan12125 it's super cool, many thanks! I'll try soon :)
