### ISSUE TITLE
Error using pip

### ISSUE THREAD

**Issue by blackeangel** [yan12125/python3-android#32]
Error. When using pip, only those modules are installed that do not require assembly.
In order to assemble the module, you need to throw gcc and so on, which is not a problem. But during the build, an error occurs that refers to the clang from ndk on the computer. How can this be fixed?

**Comment by yan12125** [comment]
You can use `CC=gcc pip install XXX` to specify the compiler you want. For further discussions, please go to #9.

**Comment by blackeangel** [comment]
> You can use `CC=gcc pip install XXX` to specify the compiler you want. For further discussions, please go to #9.

where this to write?
And what is XXX ?

**Comment by yan12125** [comment]
> where this to write?

The same place as you run pip.

> And what is XXX ?

XXX is the Python package you want to install via pip.

**Comment by blackeangel** [comment]
> > where this to write?
> 
> The same place as you run pip.
> 
> > And what is XXX ?
> 
> XXX is the Python package you want to install via pip.


no, no, no! compiler requires /home folder!

**Comment by yan12125** [comment]
Please run `CC=gcc pip install -v XXX` from the terminal and paste error messages you get.

**Comment by blackeangel** [comment]
Delete

**Comment by blackeangel** [comment]
> Please run `CC=gcc pip install -v XXX` from the terminal and paste error messages you get.


`
:/ $ su
:/ # CC=gcc pip3.9 install -v bsdiff4
Non-user install because site-packages writeable
Created temporary directory: /data/local/python3.9.0/cache/pip-ephem-wheel-cache-_e9d_mlc
Created temporary directory: /data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t
Initialized build tracking at /data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t
Created build tracker: /data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t
Entered build tracker: /data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t
Created temporary directory: /data/local/python3.9.0/cache/pip-install-kdvhxhgw
1 location(s) to search for versions of bsdiff4:
* https://pypi.org/simple/bsdiff4/
Fetching project page and analyzing links: https://pypi.org/simple/bsdiff4/
Getting page https://pypi.org/simple/bsdiff4/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/bsdiff4/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/bsdiff4/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/ed/5d/4805d347fc1c6f879ab2cb75fba8daf28caadf7684ad7cf659d87f42211c/bsdiff4-1.0.0.tar.gz#sha256=12418c88f1d6abd338f867deffedfbfb8b61e064d19e3fd6ce38c819d2ad934b (from https://pypi.org/simple/bsdiff4/), version: 1.0.0  Found link https://files.pythonhosted.org/packages/84/a6/a40fe115c6dd4b783033b2416ec8220ebd6716dee12792768f8f0ed750c5/bsdiff4-1.0.1.tar.gz#sha256=2cd6997e1ac74b603f4ec58ee967dd1ca62e8f17741250758181a15130c8feba (from https://pypi.org/simple/bsdiff4/), version: 1.0.1  Found link https://files.pythonhosted.org/packages/9b/d2/3477002b757b31a01f0dea6a03e8513fec1d8c4f5256ceb3b39b0fd368de/bsdiff4-1.1.0.tar.gz#sha256=7a016cc290a5e82bd70bec0090edfe16a74bbd4664f6071ecab2c3c0fb3926e1 (from https://pypi.org/simple/bsdiff4/), version: 1.1.0  Found link https://files.pythonhosted.org/packages/22/57/10d562a6b9c2087472107cab19a85ddb0bd3f65c75dd9c518fbd822d90e5/bsdiff4-1.1.1.tar.gz#sha256=0eb93406e8244f320f16180ded2c92bb41cb26dc9e9d3859bdc4cdf2f303b943 (from https://pypi.org/simple/bsdiff4/), version: 1.1.1  Found link https://files.pythonhosted.org/packages/64/91/432cd0e702847cf4acbf761ad3d4d5638e1aa3d4907a5c05b529313d7d87/bsdiff4-1.1.2.tar.gz#sha256=3099e4d2d2d2357051834140bb92a68790d1e6485eb4000bf149343963d7e200 (from https://pypi.org/simple/bsdiff4/), version: 1.1.2  Found link https://files.pythonhosted.org/packages/c6/d0/b8c6f63a8162dfa866a0f448b82ea4dee6230d93faa0e71ceb3429c4af42/bsdiff4-1.1.3.tar.gz#sha256=45906621bc4b88ccc3c609f999b318c1d551c0fc038c574837c8f04d021f60c1 (from https://pypi.org/simple/bsdiff4/), version: 1.1.3  Found link https://files.pythonhosted.org/packages/7c/39/5651840b031a97f12de2d2569a33d2779a5330e0acfe9b4aa2a9c48b8c63/bsdiff4-1.1.4.tar.gz#sha256=5a022ff4c1d1de87232b1c70bde50afbb98212fd246be4a867d8737173cf1f8f (from https://pypi.org/simple/bsdiff4/), version: 1.1.4  Found link https://files.pythonhosted.org/packages/12/a7/e76afa32f205469e87a0454e731bc9d57f04237da4c0e1d0801a912a1940/bsdiff4-1.1.5.tar.gz#sha256=bbe4758ecde4e9fe7d46c2cf1b6052a8fccb7b6b4dd9eb6ab0133c02e9505526 (from https://pypi.org/simple/bsdiff4/), version: 1.1.5  Found link https://files.pythonhosted.org/packages/b9/c2/34832b200eaf143f4f9a198a81e99011138fc87a1f840ffc55063d3c3b77/bsdiff4-1.1.6.tar.gz#sha256=97db4cd94acf8e4cb7c545911b412e8aa96bccc4d72eac88a30796d7b3217e84 (from https://pypi.org/simple/bsdiff4/), version: 1.1.6  Found link https://files.pythonhosted.org/packages/da/55/0c7aac4faf23079f8a53d9c9b49e92f47fe22443f2d59021d98811ee7f6b/bsdiff4-1.1.7.tar.gz#sha256=6e33ea7c2067c06055ad24fb50fa1bba84ab0d2e0694ef27fec1aeb91d952ec5 (from https://pypi.org/simple/bsdiff4/), version: 1.1.7  Found link https://files.pythonhosted.org/packages/bb/bb/e164d9ca525eac7231d9619b4b7339342b7b34d9313132d4c9f73e24b8a4/bsdiff4-1.1.8.tar.gz#sha256=e6c20d5143e0484fb7dfbf0f018470d16ad5681a76ce2594ea1bfc55b53d1181 (from https://pypi.org/simple/bsdiff4/), version: 1.1.8  Found link https://files.pythonhosted.org/packages/39/34/bd2ae6cd4b2a5d3af9173a9d7f6ecd2723ea7b0401ad807a0c7e7b50faa3/bsdiff4-1.1.9.tar.gz#sha256=a7c48ec58dc1c4a2b9fb5da05637524d5dbb1643a3df7cdc6ed105636909ff79 (from https://pypi.org/simple/bsdiff4/), version: 1.1.9Given no hashes to check 12 links for project 'bsdiff4': discarding no candidates
Using version 1.1.9 (newest of versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9)
Collecting bsdiff4
  Created temporary directory: /data/local/python3.9.0/cache/pip-unpack-pkzcrqlc
  Looking up "https://files.pythonhosted.org/packages/39/34/bd2ae6cd4b2a5d3af9173a9d7f6ecd2723ea7b0401ad807a0c7e7b50faa3/bsdiff4-1.1.9.tar.gz" in the cache
  Current age based on date: 263
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 263
  Using cached bsdiff4-1.1.9.tar.gz (8.4 kB)
  Added bsdiff4 from https://files.pythonhosted.org/packages/39/34/bd2ae6cd4b2a5d3af9173a9d7f6ecd2723ea7b0401ad807a0c7e7b50faa3/bsdiff4-1.1.9.tar.gz#sha256=a7c48ec58dc1c4a2b9fb5da05637524d5dbb1643a3df7cdc6ed105636909ff79 to build tracker '/data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t'
    Running setup.py (path:/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py) egg_info for package bsdiff4
    Created temporary directory: /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr
    Running command python setup.py egg_info
    running egg_info
    creating /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info
    writing /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/PKG-INFO
    writing dependency_links to /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/dependency_links.txt
    writing entry points to /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/entry_points.txt
    writing top-level names to /data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/top_level.txt
    writing manifest file '/data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/SOURCES.txt'
    reading manifest file '/data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/SOURCES.txt'
    writing manifest file '/data/local/python3.9.0/cache/pip-pip-egg-info-eid5swnr/bsdiff4.egg-info/SOURCES.txt'
  Source in /data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4 has version 1.1.9, which satisfies requirement bsdiff4 from https://files.pythonhosted.org/packages/39/34/bd2ae6cd4b2a5d3af9173a9d7f6ecd2723ea7b0401ad807a0c7e7b50faa3/bsdiff4-1.1.9.tar.gz#sha256=a7c48ec58dc1c4a2b9fb5da05637524d5dbb1643a3df7cdc6ed105636909ff79
  Removed bsdiff4 from https://files.pythonhosted.org/packages/39/34/bd2ae6cd4b2a5d3af9173a9d7f6ecd2723ea7b0401ad807a0c7e7b50faa3/bsdiff4-1.1.9.tar.gz#sha256=a7c48ec58dc1c4a2b9fb5da05637524d5dbb1643a3df7cdc6ed105636909ff79 from build tracker '/data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t'
Building wheels for collected packages: bsdiff4
  Created temporary directory: /data/local/python3.9.0/cache/pip-wheel-rzuflxsj
  Building wheel for bsdiff4 (setup.py) ...   Destination directory: /data/local/python3.9.0/cache/pip-wheel-rzuflxsj
  Running command /data/local/python3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"'; __file__='"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/local/python3.9.0/cache/pip-wheel-rzuflxsj
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv8l-3.9
  creating build/lib.linux-armv8l-3.9/bsdiff4
  copying bsdiff4/__init__.py -> build/lib.linux-armv8l-3.9/bsdiff4  copying bsdiff4/cli.py -> build/lib.linux-armv8l-3.9/bsdiff4
  copying bsdiff4/format.py -> build/lib.linux-armv8l-3.9/bsdiff4
  copying bsdiff4/test_all.py -> build/lib.linux-armv8l-3.9/bsdiff4  running build_ext
  building 'bsdiff4.core' extension
  creating build/temp.linux-armv8l-3.9
  creating build/temp.linux-armv8l-3.9/bsdiff4
  gcc -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/data/local/python3.9.0/include/python3.9 -c bsdiff4/core.c -o build/temp.linux-armv8l-3.9/bsdiff4/core.o
  arm-linux-androideabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
  error: command '/data/local/python3.9.0/bin/gcc' failed with exit code 1
error
  ERROR: Failed building wheel for bsdiff4
  Running setup.py clean for bsdiff4
  Running command /data/local/python3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"'; __file__='"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.linux-armv8l-3.9' (and everything under it)
  removing 'build/lib.linux-armv8l-3.9' (and everything under it)
  'build/bdist.linux-armv8l' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing 'build'
Failed to build bsdiff4
Installing collected packages: bsdiff4
  Created temporary directory: /data/local/python3.9.0/cache/pip-record-rx1qqn9g
    Running command /data/local/python3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"'; __file__='"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/local/python3.9.0/cache/pip-record-rx1qqn9g/install-record.txt --single-version-externally-managed --compile --install-headers /data/local/python3.9.0/include/python3.9/bsdiff4
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv8l-3.9
    creating build/lib.linux-armv8l-3.9/bsdiff4
    copying bsdiff4/__init__.py -> build/lib.linux-armv8l-3.9/bsdiff4
    copying bsdiff4/cli.py -> build/lib.linux-armv8l-3.9/bsdiff4
    copying bsdiff4/format.py -> build/lib.linux-armv8l-3.9/bsdiff4    copying bsdiff4/test_all.py -> build/lib.linux-armv8l-3.9/bsdiff4
    running build_ext
    building 'bsdiff4.core' extension
    creating build/temp.linux-armv8l-3.9
    creating build/temp.linux-armv8l-3.9/bsdiff4
    gcc -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/data/local/python3.9.0/include/python3.9 -c bsdiff4/core.c -o build/temp.linux-armv8l-3.9/bsdiff4/core.o
    arm-linux-androideabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
    error: command '/data/local/python3.9.0/bin/gcc' failed with exit code 1
    Running setup.py install for bsdiff4 ... error
ERROR: Command errored out with exit status 1: /data/local/python3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"'; __file__='"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/local/python3.9.0/cache/pip-record-rx1qqn9g/install-record.txt --single-version-externally-managed --compile --install-headers /data/local/python3.9.0/include/python3.9/bsdiff4 Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 827, in install
    success = install_legacy(
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 398, in run
    installed = install_given_reqs(
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 67, in install_given_reqs
    requirement.install(
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 270, in runner
    call_subprocess(
  File "/data/local/python3.9.0/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /data/local/python3.9.0/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"'; __file__='"'"'/data/local/python3.9.0/cache/pip-install-kdvhxhgw/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/local/python3.9.0/cache/pip-record-rx1qqn9g/install-record.txt --single-version-externally-managed --compile --install-headers /data/local/python3.9.0/include/python3.9/bsdiff4 Check the logs for full command output.
Removed build tracker: '/data/local/python3.9.0/cache/pip-req-tracker-ht4ams4t'
1|:/ #
`

**Comment by blackeangel** [comment]
> Please run `CC=gcc pip install -v XXX` from the terminal and paste error messages you get.

Show file
[log2.txt](https://github.com/yan12125/python3-android/files/4740870/log2.txt)

without CC=gcc
[log1.txt](https://github.com/yan12125/python3-android/files/4740873/log1.txt)

**Comment by yan12125** [comment]
> arm-linux-androideabi-gcc: error trying to exec 'cc1': execvp: No such file or directory

Your gcc is broken.

**Comment by blackeangel** [comment]
> > arm-linux-androideabi-gcc: error trying to exec 'cc1': execvp: No such file or directory
> 
> Your gcc is broken.


then why compiled in termux python3.9 with the same gcc works without errors?

**Comment by yan12125** [comment]
From what I can see, possible reasons might be:

1. Apparently you are running pip with root. As far as I know `su` does not work quite well with Termux.
2. From the following line in log2.txt, you are not using gcc from Termux but some custom one.

> error: command '/data/local/python3.9.0/bin/gcc' failed with exit code 1

---

I've just tried gcc from Termux. LDSHARED is also needed to install bsdiff4. Here is the command I use:

```
LDSHARED="gcc -shared" CC=gcc ./usr/bin/python3 -m pip -v install bsdiff4
```

A complete log can be found here: [bsdiff4.txt](https://github.com/yan12125/python3-android/files/4742052/bsdiff4.txt)
