### ISSUE TITLE
Running docker image has nothing in build

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#33]
I am running the steps to create the docker image and build. I am running the image and get to the end, but I have no build folder.

I am doing this on a windows box with WSL, but it appears you are expecting everything to be output to build.  Any thoughts?

I'm seeing an error

DEBUG:__main__:Running in /python3-android/src/Python-3.9.0b1/Android/deps/libffi-3.3: ./configure --prefix=/usr --libdir=/usr/lib --host=armv7a-linux-androideabi --disable-shared
checking build system type... x86_64-pc-linux-gnu
checking host system type... armv7a-unknown-linux-androideabi
checking target system type... armv7a-unknown-linux-androideabi
continue configure in default builddir "./armv7a-unknown-linux-androideabi"
....exec /bin/bash .././configure "--srcdir=.." "--enable-builddir=armv7a-unknown-linux-androideabi" "linux
androideabi"
.././configure: line 2300: config.log: No such file or directory
.././configure: line 2310: config.log: No such file or directory
cat: standard output: No such file or directory
Traceback (most recent call last):
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 170, in <module>
    main()
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 167, in main
    build_package(pkg_cls(args.target_arch_name, args.android_api_level))
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 145, in build_package
    pkg.build()
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 25, in build
    self.configure()
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 30, in configure
    self.run([
  File "/python3-android/src/Python-3.9.0b1/./Android/build_deps.py", line 22, in run
    subprocess.check_call(cmd, cwd=cwd)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./configure', '--prefix=/usr', '--libdir=/usr/lib', '--host=armv7a-linux-androideabi', '--disable-shared']' returned non-zero exit status 1.

**Comment by yan12125** [comment]
Hi, could you upload a full log file from the commands listed in https://github.com/yan12125/python3-android#build-using-docker and all following outputs?

**Comment by GRRedWings** [comment]
Here are the logs I managed to pull off.

[SharedLib.zip](https://github.com/yan12125/python3-android/files/5010344/SharedLib.zip)

**Comment by yan12125** [comment]
Could you try adding this flag?
```Diff
--- a/Android/build_deps.py
+++ b/Android/build_deps.py
@@ -68,6 +68,7 @@ class GDBM(Package):
 
 class LibFFI(Package):
     source = 'https://github.com/libffi/libffi/releases/download/v3.3/libffi-3.3.tar.gz'
+    configure_args = ['--disable-builddir']
 
 class LibUUID(Package):
     source = 'https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.35/util-linux-2.35.tar.xz'
```

**Comment by GRRedWings** [comment]
I apologize for being new to docker, but how do I add a patch file to the docker image?

**Comment by yan12125** [comment]
If you use the `-v` flag like what I did in https://github.com/yan12125/python3-android#build-using-docker, files in `/python3-android` in the docker are actually the same as files on the host, so changing files on the host is enough :)

**Comment by GRRedWings** [comment]
Perfect thank you. I had not used docker before Friday. So far it seems pretty straightforward.

I have done this patch, and I was able to get further in the build.  Here are the logs

[logs.zip](https://github.com/yan12125/python3-android/files/5012416/logs.zip)

**Comment by GRRedWings** [comment]
UPDATE: After looking at the log and seeing the clock skew, I ran your clean script.  Then running the build again, I was able to successfully build.  Thanks for the help!

**Comment by yan12125** [comment]
Great to hear that! By the way, does everything build without aforementioned `--disable-builddir` after fixing clock skew?

**Comment by GRRedWings** [comment]
In order to build I require the --disable-builddir.  I'm not sure if you want to add the fix to the mainline, but in order for it to run on my machine, it has to be there.

BTW: My environment is Windows 10 with WSL 2

**Comment by yan12125** [comment]
Thanks for testing! I added the flag in 96a708743051d13eea4d1d3e63bebbe0fd636d2e.
