### ISSUE TITLE
Errors building 32 but unversioned library

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#34]
With your help I'm able to build both the 32 bit and 64 bit libraries.  However, when I am trying to run these versions on the perspective platforms, I am having issues with the 32 bit library. It appears at first glance that maybe there is another place we need to make a similar change as we did in configure.ac, or more specific something with sockets?

E/stderr: Could not find platform independent libraries <prefix>E/stderr: Could not find platform dependent libraries <exec_prefix>
E/stderr: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
E/stderr: Traceback (most recent call last):
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/main.py", line 22, in <module>
E/stderr: from myAppSpace.base.main import start
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/myAppSpace/__init__.py", line 22, in <module>
E/stderr: from myAppSpace import configuration
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/myAppSpace/configuration/__init__.py", line 35, in <module>
E/stderr: from myAppSpace._platforms.android import configuration as _configuration
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/myAppSpace/_platforms/android/configuration/__init__.py", line 28, in <module>
E/stderr: from myAppSpace._platforms.common.configuration import getAllProperties, getAllENV, keyIsSet, checkForCommAdapters, \
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/myAppSpace/_platforms/common/configuration/__init__.py", line 27, in <module>
E/stderr: from myAppSpace import logging
E/stderr: File "/data/user/0/com.company.program/files/testApp/engine/myAppSpace/logging/__init__.py", line 22, in <module>
E/stderr: import logging.handlers
E/stderr: File "/data/user/0/com.company.program/files/Python32/logging/handlers.py", line 26, in <module>
E/stderr: import logging, socket, os, pickle, struct, time, re
E/stderr: File "/data/user/0/com.company.program/files/Python32/socket.py", line 51, in <module>
E/stderr: import _socket
E/stderr: ImportError: dlopen failed: library "libpython3.9.so.1.0" not found

**Comment by nverbeek** [comment]
Using readelf commands I was able to generate the following results. On the left is the 32 bit .so, on the right is the 64 bit one. You'll notice the 32 bit one for some reason has version defined, whereas the 64 does not. I believe this is our problem.

![image](https://user-images.githubusercontent.com/6087893/90533315-51874000-e146-11ea-8454-b94c2643bf5b.png)

**Comment by yan12125** [comment]
Mind to share your current Android test project?

**Comment by GRRedWings** [comment]
Try this version of the test app.

https://github.com/GRRedWings/python3-android/tree/build-32-bit-only

**Comment by yan12125** [comment]
Thanks. The problem appears to be in the `_socket` module (and possibly more). From the module extracted from your Python32.zip:
```
$ readelf -d app/src/main/assets/Python32/lib-dynload/_socket.cpython-39.so | grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libpython3.9.so.1.0]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
```
And from the module I built:
```
$ readelf -d python3-android-arm21/usr/lib/python3.9/lib-dynload/_socket.cpython-39.so | grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libpython3.9.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
```
A wild guess is that libpython3.9.so.1.0 is left somewhere so that _socket links to it. If that is not the case, please upload build logs for python3-android.

**Comment by GRRedWings** [comment]
Based on our build I'm pretty sure we do not have an old version of the library around. Here is the log.
[buildLog.log](https://github.com/yan12125/python3-android/files/5108650/buildLog.log)

Update: In re-reviewing your post, I'm going to double check everything again and make sure that there is not something that maybe got crossed in a 32 bit and 64 bit build.

**Comment by GRRedWings** [comment]
You were correct, there is something we were doing wrong. Thanks for the nudge!

**Comment by yan12125** [comment]
Great to see everything works now!
