### ISSUE TITLE
Unable to import decimal

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#35]
I've been trying hard to create a reproducible environment for this, and I think I finally did it so that you can see the output.

On a 64bit device, I can run with the 3.9 shared library. But as soon as I try to import decimal I get an exception.

I updated my test app in the Python 3.9 branch to output stderr and stdout. With that I was able to get the trace below. Permission denied?

 08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func: Traceback (most recent call last):
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/decimal.py", line 3, in <module>
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:     from _decimal import *
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func: ImportError: dlopen failed: couldn't map "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/lib-dynload/_decimal.cpython-39.so" segment 0: Permission denied
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func: During handling of the above exception, another exception occurred:
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func: Traceback (most recent call last):
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/main.py", line 16, in <module>
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:     main()
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/main.py", line 10, in main
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:     import decimal
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/decimal.py", line 8, in <module>
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:     from _pydecimal import *
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/_pydecimal.py", line 156, in <module>
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func:     import math as _math
08-27 16:53:02.802 17549-17588/com.example.pythontest E/err_thread_func: ImportError: dlopen failed: couldn't map "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/lib-dynload/math.cpython-39.so" segment 0: Permission denied

**Comment by yan12125** [comment]
`/storage/emulated/0` is on SD card, and on ordinary Android systems  does not allow loading executable files (including shared libraries). I guess extracting python libraries to somewhere under `/data` will work.

**Comment by GRRedWings** [comment]
I can try putting it somewhere else, but I had though this same device worked, using it the same way when running my 3.6 python branch.

**Comment by yan12125** [comment]
Hmm, strange. Could you check if the decimal module from Python 3.6 is actually loaded from SD card? For example, print the imported file:
```python
import _decimal
print(_decimal.__file__)
```

**Comment by GRRedWings** [comment]
The exception is thrown on the import, so I can't get to the print.  I have tried decimal and _decimal, I had been using just 'decimal'.

I did a print on the os import, below is the relevant output of that run

In this branch version of Test App I can see the line written to the file after the OS import, but it crashed as soon as it hits the import of decimal.  You should be able to reproduce on any device the error. I use Android studio and look at the LogCat output
https://github.com/GRRedWings/python3-android/blob/Test-App-3.9/AndroidApp/app/src/main/assets/main.py


**NOTE:** The way that I'm reading stderr and stdout is poor at best.  In this case it is writing out the stderr output before stdout, so things appear our of sync.
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func: Traceback (most recent call last):
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/main.py", line 19, in <module>
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func:     main()
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func:   File "/storage/emulated/0/Android/data/com.example.pythontest/files/main.py", line 11, in main
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func:     import _decimal
08-30 08:57:05.655 29266-29300/com.example.pythontest E/err_thread_func: ImportError: dlopen failed: couldn't map "/storage/emulated/0/Android/data/com.example.pythontest/files/Python64/lib-dynload/_decimal.cpython-39.so" segment 0: Permission denied
08-30 08:57:05.655 29266-29301/com.example.pythontest D/out_thread_func: /storage/emulated/0/Android/data/com.example.pythontest/files/Python64/os.py
08-30 08:57:05.655 29266-29301/com.example.pythontest D/out_thread_func: We should see this

**Comment by yan12125** [comment]
Yep the failure on importing `_decimal` on 3.9 is reasonable, and my solution is extracting files to `/data`. I'm curious as you said that it works on 3.6. Could you share results from your 3.6 branch?

**Comment by GRRedWings** [comment]
I apologize, you were correct. When I copy the assets to the data directory the test app runs. 

I need to go back and research more why I have 1 device that can not import this libary, and another that does not seem to want to run at all.

Here is the output of the file path, for what it's worth.
08-30 09:52:19.283 1829-1854/com.example.pythontest I/Java_com_example_pythontest_PythonThread_cleanupPython: We are leaving Cleanup Python
08-30 09:52:19.322 1829-1862/com.example.pythontest D/out_thread_func: /data/user/0/com.example.pythontest/files/Python64/decimal.py
08-30 09:52:19.322 1829-1862/com.example.pythontest D/out_thread_func: 3.9.0b1 (default, Aug 25 2020, 15:21:46) 
08-30 09:52:19.322 1829-1862/com.example.pythontest D/out_thread_func: [Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project e0caee08e
08-30 09:52:19.322 1829-1862/com.example.pythontest D/out_thread_func: sys.version_info(major=3, minor=9, micro=0, releaselevel='beta', serial=1)

**Comment by yan12125** [comment]
No problem! By the way, Python can import modules inside a zip file without extracting it first if `PYTHONPATH` is correctly configured. That might be an easier approach.
