### ISSUE TITLE
Precompiled native binary

### ISSUE THREAD

**Issue by eakteam** [yan12125/python3-android#37]
It would be awesome if publish to release prebuilt python for Android.
It reduces very much the time and many issues when building from scratch.

Thank you

**Comment by yan12125** [comment]
You created this issue on time! I planned to upload prebuilt binaries when Python 3.9.0 is out [1], and the latter is expected to be released the next week [2].

[1] https://github.com/yan12125/python3-android/issues/29
[2] https://www.python.org/dev/peps/pep-0596/.
