### ISSUE TITLE
Unable to build with --enable-shared

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#38]
I'm hoping I'm forgetting the right way to build it for a dynamic library, but when I try to pass in the --enable-shared flag with the docker-build.sh command you outline, it fails with an error of unknown flag. Any suggestions?

user@ubuntu:~/SPE/python3-android$ docker run --rm -it -v $(pwd):/python3-android -v /home/user/android-ndk-r21d:/android-ndk:ro --env ARCH=arm64 --enable-shared --without-ensurepip --disable-ipv6 --env ANDROID_API=23 python:3.9.0-slim /python3-android/docker-build.sh
unknown flag: --enable-shared
See 'docker run --help'.

**Comment by yan12125** [comment]
Oops, I forgot to test that case. Could you update and try:
```
docker run --rm -it -v $(pwd):/python3-android -v /home/user/android-ndk-r21d:/android-ndk:ro --env ARCH=arm64 --env ANDROID_API=23 python:3.9.0-slim /python3-android/docker-build.sh --enable-shared --without-ensurepip --disable-ipv6
```

**Comment by GRRedWings** [comment]
This made it possible for me to build with those flags.
