### ISSUE TITLE
Android 10+ question/bug

### ISSUE THREAD

**Issue by eakteam** [yan12125/python3-android#39]
So, the native libs cannot be executed anymore except native library directory.
My question is after downloaded the precompiled python, how to tell the python3.so after executing that everything it needs to run is found not in the same directory but e.x data/data/com.example.myapp/files/python/usr ?

This is very important to make it run on Android 10+

**Comment by yan12125** [comment]
Hmm, using the environment variable `PYTHONPATH`?

This issue may be helpful, too https://github.com/yan12125/python3-android/issues/24

**Comment by yan12125** [comment]
No response for a long time, and this seems similar to previous issues. Closing.
