### ISSUE TITLE
Generate interpreter shared objects (so) instead of static library (a)

### ISSUE THREAD

**Issue by lmbelo** [yan12125/python3-android#42]
It's is not self explanatory to me how to configure, make and distribute Python 3.9 for Android. Is it possible to better explain that?

**Comment by GRRedWings** [comment]
I believe that the Readme.md has instructions on how to build with docker.  
`docker run --rm -it -v $(pwd):/python3-android -v /path/to/android-ndk:/android-ndk:ro --env ARCH=arm --env ANDROID_API=21 python:3.9.0-slim /python3-android/docker-build.sh`

Do you have specific issues you are having?

**Comment by lmbelo** [comment]
Hi,
got the following error while building:

checking for armv7a-linux-androideabi-gcc... /home/lmbelo/crosscompile/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
checking for C compiler default output... configure: error: C compiler cannot create executables
Traceback (most recent call last):
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 172, in <module>
    main()
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 169, in main
    build_package(pkg_cls(args.target_arch_name, args.android_api_level))
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 147, in build_package
    pkg.build()
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 25, in build
    self.configure()
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 30, in configure
    self.run([
  File "/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/./Android/build_deps.py", line 22, in run
    subprocess.check_call(cmd, cwd=cwd)
  File "/home/lmbelo/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./configure', '--prefix=/usr', '--libdir=/usr/lib', '--host=armv7a-linux-androideabi', '--disable-shared', '--without-ada', '--enable-widec', '--without-debug', '--without-cxx-binding', '--disable-stripping']' returned non-zero exit status 77.


config.log reports the following:

configure:1709: /home/lmbelo/crosscompile/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -v </dev/null >&5
Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
Target: armv7a-unknown-linux-android21
Thread model: posix
InstalledDir: /home/lmbelo/crosscompile/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin
configure:1712: $? = 0
configure:1714: /home/lmbelo/crosscompile/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -V </dev/null >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:1717: $? = 1
configure:1737: checking for C compiler default output
configure:1740: /home/lmbelo/crosscompile/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -fPIC -I/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/Android/sysroot/usr/include -L/home/lmbelo/crosscompile/python3-android/src/Python-3.9.0/Android/sysroot/usr/lib -pie conftest.c  >&5
/usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:1743: $? = 1
configure: failed program was:
#line 1721 "configure"
#include "confdefs.h"

**Comment by lmbelo** [comment]
Is there a way to generate the interpreter shared object (.so)? Current compilation settings generates static library only.

**Comment by lmbelo** [comment]
> Is there a way to generate the interpreter shared object (.so)? Current compilation settings generates static library only.

Done! Just export enable_shared parameter equals to "yes" (export enable_shared=yes)
