### ISSUE TITLE
Serial module?

### ISSUE THREAD

**Issue by gabedude** [yan12125/python3-android#46]
Thanks this code works great...  However I am wondering if the serial module can be added.  I have a Python script that needs to access /dev/ttyS*.

Is this easy to add?  "pip3 install pyserial" seems not to work...

Thanks.

**Comment by GRRedWings** [comment]
Have you tried just adding the needed files along side your main.py  and importing it?  If all it's dependencies are there, that should work.  Quick look at the GitHub project it was all *.py in the serial folder.

**Comment by gabedude** [comment]
I just copied the code into my script from pyserial.  That worked.  Thanks
for this!

Gabe

**Comment by yan12125** [comment]
Glad to see that works! As a rule of thumb, pure-python libraries should work, while others require special tricks (#9).

And thanks a lot for helping on answering questions! @GRRedWings
