### ISSUE TITLE
How to install psutil on a cross-compiled python3?

### ISSUE THREAD

**Issue by X3eRo0** [yan12125/python3-android#47]
simply doing pip install psutil doesnt work because it downloads psutil source and tries to compile it with cc. since we dont have cc on the android it fails. even if we do we still dont have the python3-dev package which is necessary to build psutil.

any ideas?

**Comment by yan12125** [comment]
See https://github.com/yan12125/python3-android/issues/9. There is currently no simple way.

> we still dont have the python3-dev package which is necessary to build psutil.

All Python devel files (headers, libraries) are in [pre-built tarballs](https://github.com/yan12125/python3-android/releases). I don't think they can be directly used, though.
