### ISSUE TITLE
Do you consider to use MIT instead of WTFPL License?

### ISSUE THREAD

**Issue by bebethecat** [yan12125/python3-android#48]
Thanks for the great work to make python3 available on android. Would you consider to use MIT License to make to project explicity available for wider usage?

**Comment by yan12125** [comment]
Is there an advantage for MIT license over WTFPL? I think WTFPL already allows you to do whatever you want.

Also, as far as I know, changing the license requires acknowledgements from [all contributors](https://github.com/yan12125/python3-android/graphs/contributors) @GRRedWings @Shizmob ?

Another side note - apparently the license file added by Shizmob in https://github.com/rave-engine/python3-android/commit/03b208916a3a1741b676dc5371bfb08c8f211892, and Sam Hocevar is [the author of the license text](https://en.wikipedia.org/wiki/Sam_Hocevar), not the author of the software

**Comment by GRRedWings** [comment]
I'm not a lawyer or an expert on licensing, but I took the WTFPL to mean, I can change the license if I want.  I changed mine to an Apache license as it was a little awkward to explain the license to anyone who asked.

That said, I feel that the WTFPL is more open than the MIT or Apache license, it seems clear to me that the WTFPL means there are no rules, just do what makes you happy.

**Comment by yan12125** [comment]
> I can change the license if I want.

I guess not but I'm not a lawyer, either.

> I changed mine to an Apache license

Just in case - I agree to relicense my prior contributions under Apache

> That said, I feel that the WTFPL is more open than the MIT or Apache license

I have a similar feeling :)

**Comment by GRRedWings** [comment]
I also agree to relicense as well.  

I feel we won't hear much from Shizmob.  I had reached out years ago, and never heard a response.

**Comment by shizmob** [comment]
Hi, I'm still around! I'm just bad at remembering to respond to things; I also don't really have the mental cycles available to contribute anything meaningful technically at this point, but sorry for leaving you on read @GRRedWings! I honestly did not intend to, and you've been doing great work with the project.

As @yan12125 noted, Sam Hocevar is the author of the WTFPL, not the original code. That said, I'm fine with my contributions being relicensed to MIT or whatever, as it's a freedom the WTFPL also provides.

**Comment by yan12125** [comment]
Thanks Shizmob for the confirmation as well as past awesome work for this project! Now we're ready for relicensing. Anyway, I think among serious licenses, 0-BSD or CC0 is closer to WTFPL. Let's see if @bebethecat is OK with any of it.

**Comment by bebethecat** [comment]
I think 0-BSD is very good. I will update the PR to use 0-BSD

**Comment by GRRedWings** [comment]
I have also updated my fork to have the same license.  Keep it consistent.

**Comment by shizmob** [comment]
BSD0 is a nice license, so aside from of course being technically allowed to, I also approve in spirit. :)

**Comment by GRRedWings** [comment]
As @yan12125 mentioned earlier, thank you @Shizmob  for kicking this off and all the help along the way.  Both of you guys have made it so much easier to do Python on Android.

And if either of you are up for a challenge, I'd like to add x86 to the build.  When I have time I'll start looking.

**Comment by shizmob** [comment]
And thanks to both of you for picking up where I left off and making it even better! When I could find the time and memory to respond, I've always enjoyed our interactions @GRRedWings; thanks for putting up with my flaky responsiveness in particular. 😅
